name: Feature Request
description: Suggest an idea or a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping make VDH media center better! Describe your idea below.

  - type: textarea
    id: description
    attributes:
      label: Describe your idea
      description: What would you like to see added or improved?
      placeholder: "It would be great if the application could ..."
    validations:
      required: true
